services:
  - type: web
    name: my-puppeteer-app
    env: node
    region: oregon
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
